# Generated by Django 2.0 on 2018-04-16 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20180416_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='upddated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 16, 13, 2, 59, 613524)),
        ),
        migrations.AlterField(
            model_name='quotient',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 16, 13, 2, 59, 614107)),
        ),
    ]
